CSHARP-825 Add test support for OSS clusters and bring back OSS appveyor.yml (#11)

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -3,59 +3,70 @@ schedules:
     # Run short suite on commit
     schedule: per_commit
     matrix:
-      exclude:      
-        # Only build with latest for mono and netstandard 1.5
+      exclude:
+      # net45(mono) and netstandard1.5 build 3.11 and dse-6.7 only
         - dotnet: ['mono', 'netcoreapp2.0']
-          cassandra: ['dse-4.8', 'dse-5.1', 'dse-6.0', 'dse-6.7']
-        # Only build with latest minor for each all majors for netstandard 2.0
+          cassandra: ['2.1', '2.2', '3.0', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
+      # netstandard2.0 build latest minors
         - dotnet: 'netcoreapp2.1'
-          cassandra: ['dse-6.0']
+          cassandra: ['2.1', '3.0', 'dse-5.0', 'dse-6.0', 'dse-6.8']
   nightly:
-    # Run full suite nightly on change for all primary branches if they have changes.
+    # nightly job for primary branches to run all configs.
     schedule: nightly
     branches:
-      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, dse, master, etc).
-      include: ["/((\\d+(\\.[\\dx]+)+)|dse|master)/"]
+      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, master, etc).
+      include: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
   adhoc:
-    # Adhoc job for non-primary braches that doesn't have a schedule but may be used to run all configs.
+    # adhoc job for non-primary braches that doesn't have a schedule but may be used to run all configs.
     schedule: adhoc
-    enable_pull_requests: true
     branches:
-      exclude: ["/((\\d+(\\.[\\dx]+)+)|dse|master)/"]
+      exclude: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
 os:
   - ubuntu/bionic64/csharp-driver
 cassandra:
-  - dse-4.8
-  - dse-5.1
-  - dse-6.0
-  - dse-6.7
-  - dse-6.8
+  - '2.1'
+  - '2.2'
+  - '3.0'
+  - '3.11'
+  - 'dse-4.8'
+  - 'dse-5.0'
+  - 'dse-5.1'
+  - 'dse-6.0'
+  - 'dse-6.7'
+  - 'dse-6.8'
 dotnet:
   - 'mono'
   - 'netcoreapp2.0'
   - 'netcoreapp2.1'
 build:
   - script: |
-      export CASS_VERSION_SNI='dse-6.8'
+      export CASS_VERSION_SNI='dse-6.7'
       
       # Set the Java paths (for CCM)
       export JAVA_HOME=$CCM_JAVA_HOME
       export PATH=$JAVA_HOME/bin:$PATH
       export SIMULACRON_PATH=$HOME/simulacron.jar
-      export CCM_PATH=$HOME/ccm
-      export DSE_INITIAL_IPPREFIX="127.0.0."
-      export DSE_BRANCH=$CCM_BRANCH
-      export DSE_VERSION=$CCM_VERSION
-      export DSE_IN_REMOTE_SERVER="false"
 
-      if [ $DSE_VERSION = '6.0' ]; then
-          echo "Setting DSE 6.0 install-dir"
-          export DSE_PATH=$CCM_INSTALL_DIR
+      if [[ $CASSANDRA_VERSION == dse-* ]] ;
+      then
+          export CCM_PATH=$HOME/ccm
+          export DSE_BRANCH=$CCM_BRANCH
+          export DSE_VERSION=$CCM_VERSION
+          export DSE_INITIAL_IPPREFIX="127.0.0."
+          export DSE_IN_REMOTE_SERVER="false"
+                
+          if [ $DSE_VERSION = '6.0' ]; then
+              echo "Setting DSE 6.0 install-dir"
+              export DSE_PATH=$CCM_INSTALL_DIR
+          fi
+          
+          echo $DSE_VERSION
+          echo $DSE_PATH
+          echo $DSE_INITIAL_IPPREFIX
+          echo $DSE_IN_REMOTE_SERVER
+          echo $DSE_INITIAL_IPPREFIX
       fi
-      
-      echo $DSE_VERSION
-      echo $DSE_PATH
-      echo $DSE_INITIAL_IPPREFIX
+
       echo $CSHARP_VERSION
 
       # Define Cassandra runtime
@@ -78,8 +89,7 @@ build:
       echo $SNI_CERTIFICATE_PATH
       echo $SNI_CA_PATH
       
-      ls "${HOME}/proxy/"
- 
+      ls "${HOME}/proxy/" 
 
       # Download and uncompress saxon
       mkdir saxon
@@ -95,18 +105,16 @@ build:
           export -f nuget
 
           # Install the required packages
-          export EnableNuGetPackageRestore=true
-          msbuild /t:restore /v:m src/Cassandra.sln
           nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
 
           # Compile the driver and test code
+          msbuild /t:restore /v:m src/Cassandra.sln
           msbuild /p:Configuration=Release /v:m /p:DynamicConstants=LINUX src/Cassandra.sln
 
           # Run the tests
-          echo "==========RUNNING FULL SUITE OF TESTS=========="
           mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Cassandra.IntegrationTests/bin/Release/net452/Cassandra.IntegrationTests.dll --where "cat != long && cat != memory" --labels=All --result:"TestResult_nunit.xml" || error=true
           java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_nunit.xml tools/nunit3-junit.xslt
-
+          
           #Fail the build if there was an error
           if [ $error ]
           then 
@@ -121,10 +129,9 @@ build:
           dotnet restore src
 
           # Run the tests
-          echo "==========RUNNING FULL SUITE OF TESTS=========="
-          dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -v n -f $DOTNET_VERSION -c Release --filter "(TestCategory!=long)&(TestCategory!=memory)" --logger "xunit;LogFilePath=../../TestResult_xunit.xml"  || error=true
+          dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -v n -f $DOTNET_VERSION -c Release --filter "(TestCategory!=long)&(TestCategory!=memory)" --logger "xunit;LogFilePath=../../TestResult_xunit.xml" || error=true
           java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_xunit.xml tools/JUnitXml.xslt
-
+          
           #Fail the build if there was an error
           if [ $error ]
           then 
