change project names in CI yml files

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -96,15 +96,15 @@ build:
 
           # Install the required packages
           export EnableNuGetPackageRestore=true
-          msbuild /t:restore /v:m src/Dse.sln
+          msbuild /t:restore /v:m src/Cassandra.sln
           nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
 
           # Compile the driver and test code
-          msbuild /p:Configuration=Release /v:m /p:DynamicConstants=LINUX src/Dse.sln
+          msbuild /p:Configuration=Release /v:m /p:DynamicConstants=LINUX src/Cassandra.sln
 
           # Run the tests
           echo "==========RUNNING FULL SUITE OF TESTS=========="
-          mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Dse.Test.Integration/bin/Release/net452/Dse.Test.Integration.dll --where "cat != long && cat != memory" --labels=All --result:"TestResult_nunit.xml" || error=true
+          mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Cassandra.IntegrationTests/bin/Release/net452/Cassandra.IntegrationTests.dll --where "cat != long && cat != memory" --labels=All --result:"TestResult_nunit.xml" || error=true
           java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_nunit.xml tools/nunit3-junit.xslt
 
           #Fail the build if there was an error
@@ -122,7 +122,7 @@ build:
 
           # Run the tests
           echo "==========RUNNING FULL SUITE OF TESTS=========="
-          dotnet test src/Dse.Test.Integration/Dse.Test.Integration.csproj -v n -f $DOTNET_VERSION -c Release --filter "(TestCategory!=long)&(TestCategory!=memory)" --logger "xunit;LogFilePath=../../TestResult_xunit.xml"  || error=true
+          dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -v n -f $DOTNET_VERSION -c Release --filter "(TestCategory!=long)&(TestCategory!=memory)" --logger "xunit;LogFilePath=../../TestResult_xunit.xml"  || error=true
           java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_xunit.xml tools/JUnitXml.xslt
 
           #Fail the build if there was an error
