Changed build yaml to use dotnet runtime and publish test report in mono test failures

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -1,15 +1,37 @@
+schedules:
+  commit:
+    # Run short suite on commit
+    schedule: per_commit
+    matrix:
+      exclude:
+        # Only build with latest for mono and netstandard 2.0
+        - dotnet: ['mono', 'netcoreapp2.1']
+          cassandra: ['2.1', '2.2', '3.0']
+        # Only build with 2.1 and latest for netstandard 1.5
+        - dotnet: 'netcoreapp2.0'
+          cassandra: ['2.2', '3.0']
+  nightly:
+    # nightly job for primary branches to run all configs.
+    schedule: nightly
+    branches:
+      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, master, etc).
+      include: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
+  adhoc:
+    # adhoc job for non-primary braches that doesn't have a schedule but may be used to run all configs.
+    schedule: adhoc
+    branches:
+      exclude: ["/((\\d+(\\.[\\dx]+)+)|master)/"]
 os:
   - ubuntu/bionic64/csharp-driver
 cassandra:
-  - 2.1
-  - 2.2
-  - 3.0
+  - '2.1'
+  - '2.2'
+  - '3.0'
   - '3.11'
-env:
-  CSHARP_VERSION:
-    - mono
-    - netcoreapp2.0
-    - netcoreapp2.1
+dotnet:
+  - 'mono'
+  - 'netcoreapp2.0'
+  - 'netcoreapp2.1'
 build:
   - script: |
       # Set the Java paths (for CCM)
@@ -29,7 +51,7 @@ build:
       curl -L -o saxon/SaxonHE9-8-0-12J.zip https://downloads.sourceforge.net/project/saxon/Saxon-HE/9.8/SaxonHE9-8-0-12J.zip
       unzip saxon/SaxonHE9-8-0-12J.zip -d saxon
  
-      if [ $CSHARP_VERSION = 'mono' ]; then
+      if [ $DOTNET_VERSION = 'mono' ]; then
           echo "========== Starting Mono Build =========="
           mono --version
           # Define alias for Nuget
@@ -46,10 +68,17 @@ build:
           msbuild /p:Configuration=Release /v:m /p:DynamicConstants=LINUX src/Cassandra.sln
 
           # Run the tests
-          mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Cassandra.IntegrationTests/bin/Release/net452/Cassandra.IntegrationTests.dll --where:cat=short --labels=All --result:"TestResult_nunit3.xml"
+          mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe src/Cassandra.IntegrationTests/bin/Release/net452/Cassandra.IntegrationTests.dll --where:cat=short --labels=All --result:"TestResult_nunit3.xml" || error=true
+          
           java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_nunit3.xml tools/nunit3-xunit.xslt
+          
+          #Fail the build if there was an error
+          if [ $error ]
+          then 
+              exit -1
+          fi
       else
-          echo "========== Starting .NET Core SDK Build =========="
+          echo "========== Starting .NET Core Build =========="
           export DOTNET_CLI_TELEMETRY_OPTOUT=1
           dotnet --version
 
@@ -57,7 +86,7 @@ build:
           dotnet restore src
 
           # Run the tests
-          dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f $CSHARP_VERSION -c Release --filter TestCategory=short --logger "trx;LogFileName=../../../TestResult_trx.xml" || error=true
+          dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f $DOTNET_VERSION -c Release --filter TestCategory=short --logger "trx;LogFileName=../../../TestResult_trx.xml" || error=true
           
           java -jar saxon/saxon9he.jar -o:TestResult.xml TestResult_trx.xml tools/trx-to-junit.xslt
           
